[tool.poetry]
name = "bot"
version = "0.1.0"
description = "bot"
authors = ["xmmmmmovo"]
readme = "README.md"

[tool.nonebot]
plugins = ["nonebot_plugin_apscheduler"]
plugin_dirs = ["src/plugins", "src/middleware"]
